### ISSUE TITLE
"Compatible" hides valid MSU

### ISSUE THREAD

**Issue by Alaszun** [MattEqualsCoder/MSURandomizer#12]
Hey, not really sure how to debug or provide appropriate information here, but if I have the filter set to "Compatible" it's hiding MSUs that I have used as valid MSUs in ALTTP before.

Specifically I am using the Sonic 2 MSU, and it gets filtered out with compatible on. If I set the filter to "All" it will show up, and if I use it it works correctly.

**Comment by Alaszun** [comment]
I should probably have written this better. If you look at the UI it does show as "Unknown" instead of Link to the Past.

![image](https://github.com/MattEqualsCoder/MSURandomizer/assets/27381189/d9c6644f-006b-4437-8413-58d8e0f12a12)

I guess the question here is why is this MSU which is a valid ALTTPR MSU is showing as unknown. Is it looking for specific files?
![image](https://github.com/MattEqualsCoder/MSURandomizer/assets/27381189/76287d97-03f1-4046-ba38-98994b25f1eb)

**Comment by MattEqualsCoder** [comment]
Won't bore you with the details, but I think what's most likely the issue is with how I try to distinguish between Super Metroid MSUs with the future extended tracks and Z3 MSUs. I'm overhauling the way all this works in the next version so that it'll hopefully be better. Worst case scenario, I'm adding in a function into the next version for you to be able to override default MSU types.

That being said, there shouldn't be much of a downside of selecting Unknown tracks until the new version comes out in a couple weeks.

(BTW, nice choices with Steins;Gate and Umineko MSUs 👍)

**Comment by Alaszun** [comment]
I'm glad you like them! The S;G is a personal one I made (the Danganronpa is also a personal one, not Zelga's one)--I don't think anyone else has actually taken that one on. The Umineko one I just love the music from that series so much.

This is a small potatoes thing and not a problem to deal with at all, just figured if something was broken you'd probably want to know. Sounds like you're aware and it won't matter. Thanks for the response!

**Comment by MattEqualsCoder** [comment]
I've created a release candidate here: https://github.com/MattEqualsCoder/MSURandomizer/releases/tag/v0.9.7-rc.1

The MSU detection is completely different and may not work in 100% of cases still because there are some unusual corner cases where people do things differently, but you can now override the MSU type if needed. Let me know if you run into any problems.
