### ISSUE TITLE
Selection seems to be over-eager and not match up with what is actually selected.

### ISSUE THREAD

**Issue by Alaszun** [MattEqualsCoder/MSURandomizer#13]
The selected list seems to be over-eager in what it selects.

![image](https://github.com/MattEqualsCoder/MSURandomizer/assets/27381189/2fea4f3c-7abc-447b-83f9-bb851c1d4b79)

Here were my rough reproduction steps:

1. Press Select None
2. Select some MSUs (screenshot above should show what I selected)
3. Create Shuffled MSU

Yet no matter what I seem to select it seems to greedily grab more MSUs than I selected. For instance, in this case it definitely included both FF7 and Naruto which are not selected.

I thought I might have just user errored at first, but this has happened 5-6 times, so I'm pretty sure something is grabbing too much here.

**Comment by MattEqualsCoder** [comment]
Ah, yeah. This is an issue I found that should also be fixed in the next version.

For whatever reason, I didn't use the full path so it gets confused when msus have generic file names (like alttp_msu in the case of Naruto and probably some others you have). If I get the time, I may try to get a hotfix out in the next couple days for this before the next larger update.

**Comment by Alaszun** [comment]
Ahhh, the path makes so much sense here! I was trying to figure out what the MSUs that were failing this had in common, and just looking for alttp_msu.* makes a lot of sense.

**Comment by MattEqualsCoder** [comment]
The new release candidate should take care of this as it uses the full path as a key for keeping track of which MSU packs you have selected.

**Comment by Alaszun** [comment]
Hey Matt, can confirm this is fixed in pre-release!
